matrix:
  rows:
    #        - { os: linux,   arch: x64,   platform: linux-x86_64 }
    #        - { os: linux,   arch: arm64, platform: linux-aarch_64 }
    #        - { os: macos,   arch: x64,   platform: osx-x86_64 }
    - { os: macos, arch: arm64, platform: osx-aarch_64 }

project:
  name: myapp
  version: 1.0.0
  description: Native CLI built with GraalVM
  authors:
    - Julien May
  license: Apache-2.0
  copyright: Julien 2025
  links:
    homepage: https://julien-may.github.io/zero-jdk/

assemble:
  archive:
    zjdk:
      active: ALWAYS
      formats: [ TAR_GZ ]
      applyDefaultMatrix: true
      archiveName: '{{distributionName}}-{{projectVersion}}-{{matrix.os}}-{{matrix.arch}}'

      fileSets:
        - input: target
          includes: [ zjdk ]
          output: .

distributions:
  zjdk:
    type: BINARY
    executable:
      name: zjdk
    extraProperties:
      individualChecksum: true

release:
  github:
    enabled: true
    draft: false
    skipTag: false
    overwrite: true
    changelog:
      formatted: ALWAYS
