project:
  name: myapp
  version: 1.0.0
  description: Native CLI built with GraalVM
  authors:
    - Julien May
  license: Apache-2.0
  copyright: Julien - 2025
  links:
    homepage: https://julien-may.github.io/zero-jdk/
    documentation: https://julien-may.github.io/zero-jdk/

release:
  github:
    enabled: true
    draft: false
    skipTag: false
    overwrite: true
    changelog:
      formatted: ALWAYS

distributions:
  zjdk:
    type: BINARY
    executable:
      name: zjdk
    extraProperties:
      individualChecksum: true
    artifacts:
#      - path: artifacts/zjdk-linux-x64
#        platform: linux-x86_64
#      - path: artifacts/zjdk-linux-arm64
#        platform: linux-aarch_64
#      - path: artifacts/zjdk-macos-x64
#        platform: osx-x86_64
      - path: artifacts/zjdk-macos-arm64
        platform: osx-aarch_64
        extraProperties:
          graalVMNativeImage: true
